#!/bin/bash

case "$1" in
"adapter")
    # we need something different in order to pass the classpath of the current project
    # you must specify: appClassName (extends AdapterApp class) , cluster name, output stream name
    # current syntax is not yet straightforward:
    # example : ./s4 adapter -cluster=c1 -appClass=org.apache.s4.example.twitter.TwitterInputAdapter -p=s4.adapter.output.stream:s1
	shift 1
	/opt/bin/gradlew cp
	java -cp `cat classpath.txt` org.apache.s4.core.Main $@
;;
*)
	echo "calling referenced s4 script : /opt/bin/s4"
	(cd /opt/build/java/s4 && /opt/bin/s4 $@)
;;
esac
